service: chrome-lambda
provider:
  name: aws
  runtime: nodejs10.x
  timeout: 180
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:ListBucket'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: MainBucket
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        Fn::Join:
          - ''
          - - 'arn:aws:s3:::'
            - Ref: MainBucket
            - '/*'

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - src/fixtures/**
    - src/__tests__/**
    - .*
    - node_modules/aws-sdk/**

functions:
  headless-chrome:
    handler: src/index.handler
    memorySize: 1600MB
    timeout: 240
    environment:
      S3_BUCKET: ${env:S3_BUCKET}
    events:
      - http:
          path: /
          method: post
          response:
            headers:
              Content-Type: 'image/png'

resources:
  Resources:
    MainBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${env:S3_BUCKET}

custom:
  chrome:
    flags:
        # - --window-size=300,400 # Letter size
        - --hide-scrollbars
        - --ignore-certificate-errors
    functions:
        - headless-chrome

