service: chrome-lambda
provider:
  name: aws
  runtime: nodejs10.x
  timeout: 180

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

package:
  exclude:
    - node_modules/puppeteer/.local-chromium/**
    - src/__tests__/**
    - .*
    - node_modules/aws-sdk/**

functions:
  headless-chrome:
    handler: src/index.handler
    memorySize: 1600MB
    timeout: 240
    environment:
      S3_BUCKET: ${env:S3_BUCKET}
    events:
      - http:
          path: /
          method: post
          response:
            headers:
              Content-Type: 'image/png'

custom:
  chrome:
    flags:
        # - --window-size=300,400 # Letter size
        - --hide-scrollbars
        - --ignore-certificate-errors
    functions:
        - headless-chrome

